// Generated by gencpp from file tutorial_msgs/RobotPos.msg
// DO NOT EDIT!


#ifndef TUTORIAL_MSGS_MESSAGE_ROBOTPOS_H
#define TUTORIAL_MSGS_MESSAGE_ROBOTPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace tutorial_msgs
{
template <class ContainerAllocator>
struct RobotPos_
{
  typedef RobotPos_<ContainerAllocator> Type;

  RobotPos_()
    : name()
    , pos()  {
    }
  RobotPos_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , pos(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::tutorial_msgs::RobotPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_msgs::RobotPos_<ContainerAllocator> const> ConstPtr;

}; // struct RobotPos_

typedef ::tutorial_msgs::RobotPos_<std::allocator<void> > RobotPos;

typedef boost::shared_ptr< ::tutorial_msgs::RobotPos > RobotPosPtr;
typedef boost::shared_ptr< ::tutorial_msgs::RobotPos const> RobotPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_msgs::RobotPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_msgs::RobotPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tutorial_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'tutorial_msgs': ['/home/eirikolb/M-drive/Documents/In3140/ROS/3140gruppeoppgave/tutorial_ws/src/tutorial_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_msgs::RobotPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_msgs::RobotPos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_msgs::RobotPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_msgs::RobotPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_msgs::RobotPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_msgs::RobotPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_msgs::RobotPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70afeb84f12dd0e4126fdef53df0eb32";
  }

  static const char* value(const ::tutorial_msgs::RobotPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70afeb84f12dd0e4ULL;
  static const uint64_t static_value2 = 0x126fdef53df0eb32ULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_msgs::RobotPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_msgs/RobotPos";
  }

  static const char* value(const ::tutorial_msgs::RobotPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_msgs::RobotPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name \n\
geometry_msgs/Point pos\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::tutorial_msgs::RobotPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_msgs::RobotPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_msgs::RobotPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_msgs::RobotPos_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_MSGS_MESSAGE_ROBOTPOS_H
